# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyAndSell', '0002_sessiontoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=80),
        ),
    ]
